addSbtPlugin("org.scala-js"  % "sbt-scalajs"      % "1.20.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp"          % "2.3.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"     % "3.12.2")
addSbtPlugin("com.github.sbt" % "sbt-site-paradox" % "1.7.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"    % "0.12.0")
