remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: Apion
description: A type-safe HTTP server framework for Scala.js that combines Express-style ergonomics with Scala's powerful type system

# Logo settings
logo: "/assets/images/apion.png"
favicon_ico: "/assets/images/apion.ico"

# Enable search
search_enabled: true

# Enable dark/light mode
color_scheme: dark  # Default theme
enable_theme_switcher: true

# Navigation structure
nav:
  - API: "/api"
  - Releases: "/releases"

# Additional configuration for Just-the-Docs
aux_links:
  "Apion on GitHub":
    - "https://github.com/edadma/apion"

# Footer content
footer_content: "Copyright &copy; 2025 edadma. Distributed under an ISC license."
